version: '3.7'

services:
  db:
    image: postgres:latest
    container_name: baza_systemy_chmurowe
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: postgre
    volumes:
      - ./Database/data/part_categories.csv:/data/part_categories.csv
      - ./Database/data/parts.csv:/data/parts.csv
      - ./Database/data/sets.csv:/data/sets.csv
      - ./Database/data/themes.csv:/data/themes.csv
      - ./Database/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
     build: ./Backend
     container_name: backend_systemy_chmurowe
     restart: always
     volumes:
       - .:/Backend
     ports:
       - "4000:4000"
     command:
        - python
        - ./Backend/app.py
     depends_on:
        db:
          condition: service_healthy
  frontend:
     build: ./Frontend
     container_name: frontend_systemy_chmurowe
     restart: always
     ports:
       - "5173:5173"
     command:
       - npm
       - run
       - dev
     depends_on:
       - backend
